project_id = "dlgrlanmnvpwladkhexb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.get-all-users]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false