// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlgrlanmnvpwladkhexb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsZ3JsYW5tbnZwd2xhZGtoZXhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTY2NTAsImV4cCI6MjA2ODU5MjY1MH0.ql17Vfaz7fEFFE9HxX2VxYJBo50vUghXKZZgCUFo9HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});